/**
 * Step 3 — Image generation with A/B variants.
 *
 * Uses the image prompt generated by the unified Chef Augustin agent.
 * Falls back to a deterministic prompt if no imagePrompt is provided.
 */

import { runImage } from "@/lib/agents/ideogram"
import { uploadImage } from "@/lib/agents/cloudinary"
import { optimizeImagePrompt } from "@/lib/skills"
import { validateImage } from "@/lib/image-validator"
import { appendLog, logEntry } from "../helpers"
import { logPipelineError } from "@/lib/queries"

const IMAGE_VARIANT_COUNT = Math.min(
  parseInt(process.env.IMAGE_VARIANT_COUNT ?? "2", 10) || 2,
  3,
)

export interface ImagePhaseResult {
  heroImageUrl: string | null
  imageVariants: Array<{ label: string; url: string; prompt: string }>
  degraded: boolean
}

export async function runImagePhase(
  step: { run: (name: string, fn: () => Promise<unknown>) => Promise<unknown>; sleep: (name: string, dur: string) => Promise<void> },
  recipeId: number,
  recipe: { title: string; tags: string[]; imagePrompt?: string },
  keyword: string,
): Promise<ImagePhaseResult> {
  let degraded = false

  // Use the unified agent's image prompt, or fall back to the deterministic 10-layer builder
  const imagePrompt = optimizeImagePrompt({
    title: recipe.title,
    tags: recipe.tags,
    imagePrompt: recipe.imagePrompt,
    keyword,
  })

  await appendLog(recipeId, logEntry("Image Prompt", "done", `Using image prompt (${imagePrompt.length} chars)`))
  await step.sleep("sleep-after-image-prompt", "2s")

  // ── Generate and upload image variants ──────────────────────────────────
  const imageVariants: Array<{ label: string; url: string; prompt: string }> = []
  let heroImageUrl: string | null = null

  for (let vi = 0; vi < IMAGE_VARIANT_COUNT; vi++) {
    try {
      const buffer = (await step.run(`gen-image-v${vi}`, async () => {
        await appendLog(recipeId, logEntry("Image Gen", "running", `Variant ${vi + 1}/${IMAGE_VARIANT_COUNT}`))
        const result = await runImage(imagePrompt)
        await appendLog(recipeId, logEntry("Image Gen", "done", `Variant ${vi + 1} generated — ${result.length} bytes`))
        return result
      })) as Buffer

      const imageUrl = (await step.run(`upload-image-v${vi}`, async () => {
        const url = await uploadImage(buffer, `${recipe.title}-v${vi}`)
        await appendLog(recipeId, logEntry("Image Upload", "done", `Uploaded to Cloudinary — v${vi}`))
        return url
      })) as string

      imageVariants.push({ label: `Variant ${vi + 1}`, url: imageUrl, prompt: imagePrompt })
      if (!heroImageUrl) heroImageUrl = imageUrl

      // Non-blocking image quality validation (v13 — was dead code before Phase 3)
      try {
        const imgValidation = await validateImage(imageUrl, { requireAltText: true, altText: recipe.title })
        if (!imgValidation.passed) {
          const issues = imgValidation.errors.map(e => e.message).join("; ")
          await appendLog(recipeId, logEntry("Image Validator", "done",
            `Variant ${vi + 1} has ${imgValidation.errors.length} issue(s): ${issues}`))
        }
      } catch (imgErr) {
        // Image validation failure is non-blocking — log and continue
        await appendLog(recipeId, logEntry("Image Validator", "error",
          `Validation failed for v${vi}: ${(imgErr as Error).message}`))
      }
    } catch (err) {
      degraded = true
      await logPipelineError({
        recipeId, stepName: `image-gen-v${vi}`,
        errorType: "unknown", message: (err as Error).message, severity: "warning",
      })
    }
  }

  return { heroImageUrl, imageVariants, degraded }
}
