/**
 * Step 3 — Image generation with A/B variants.
 *
 * Uses the image prompt generated by the unified Chef Augustin agent.
 * Falls back to a deterministic prompt if no imagePrompt is provided.
 */

import { runImage } from "@/lib/agents/ideogram"
import { uploadImage } from "@/lib/agents/cloudinary"
import { appendLog, logEntry, isRecoverableError } from "../helpers"
import { logPipelineError } from "@/lib/queries"

const IMAGE_VARIANT_COUNT = Math.min(
  parseInt(process.env.IMAGE_VARIANT_COUNT ?? "2", 10) || 2,
  3,
)

export interface ImagePhaseResult {
  heroImageUrl: string | null
  imageVariants: Array<{ label: string; url: string; prompt: string }>
  degraded: boolean
}

export async function runImagePhase(
  step: { run: (name: string, fn: () => Promise<unknown>) => Promise<unknown>; sleep: (name: string, dur: string) => Promise<void> },
  recipeId: number,
  recipe: { title: string; tags: string[]; imagePrompt?: string },
  keyword: string,
): Promise<ImagePhaseResult> {
  let degraded = false

  // Use the unified agent's image prompt, or fall back to a deterministic one
  const imagePrompt = recipe.imagePrompt?.trim()
    ? recipe.imagePrompt
    : `Professional food photography of ${recipe.title}, natural window light, styled on rustic ceramic plate, overhead flat-lay composition, shallow depth of field, warm tones, 2:3 vertical aspect ratio, editorial food photography`

  await appendLog(recipeId, logEntry("Image Prompt", "done", `Using image prompt (${imagePrompt.length} chars)`))
  await step.sleep("sleep-after-image-prompt", "2s")

  // ── Generate and upload image variants ──────────────────────────────────
  const imageVariants: Array<{ label: string; url: string; prompt: string }> = []
  let heroImageUrl: string | null = null

  for (let vi = 0; vi < IMAGE_VARIANT_COUNT; vi++) {
    try {
      const buffer = (await step.run(`gen-image-v${vi}`, async () => {
        await appendLog(recipeId, logEntry("Image Gen", "running", `Variant ${vi + 1}/${IMAGE_VARIANT_COUNT}`))
        const result = await runImage(imagePrompt)
        await appendLog(recipeId, logEntry("Image Gen", "done", `Variant ${vi + 1} generated — ${result.length} bytes`))
        return result
      })) as Buffer

      const imageUrl = (await step.run(`upload-image-v${vi}`, async () => {
        const url = await uploadImage(buffer, `${recipe.title}-v${vi}`)
        await appendLog(recipeId, logEntry("Image Upload", "done", `Uploaded to Cloudinary — v${vi}`))
        return url
      })) as string

      imageVariants.push({ label: `Variant ${vi + 1}`, url: imageUrl, prompt: imagePrompt })
      if (!heroImageUrl) heroImageUrl = imageUrl
    } catch (err) {
      degraded = true
      await logPipelineError({
        recipeId, stepName: `image-gen-v${vi}`,
        errorType: "unknown", message: (err as Error).message, severity: "warning",
      })
    }
  }

  return { heroImageUrl, imageVariants, degraded }
}
