/**
 * Step 3 — Image generation with A/B variants.
 *
 * Uses the image prompt generated by the unified Chef Augustin agent.
 * Falls back to a deterministic prompt if no imagePrompt is provided.
 */

import { runImage } from "@/lib/agents/ideogram"
import { uploadImage } from "@/lib/agents/cloudinary"
import { optimizeImagePrompt } from "@/lib/skills"
import { validateImage } from "@/lib/image-validator"
import { appendLog, logEntry } from "../helpers"
import { logPipelineError } from "@/lib/queries"

const IMAGE_VARIANT_COUNT = Math.min(
  parseInt(process.env.IMAGE_VARIANT_COUNT ?? "2", 10) || 2,
  3,
)

export interface ImagePhaseResult {
  heroImageUrl: string | null
  imageVariants: Array<{ label: string; url: string; prompt: string }>
  degraded: boolean
}

export async function runImagePhase(
  recipeId: number,
  recipe: { title: string; tags: string[]; imagePrompt?: string },
  keyword: string,
): Promise<ImagePhaseResult> {
  let degraded = false

  const imagePrompt = optimizeImagePrompt({
    title: recipe.title,
    tags: recipe.tags,
    imagePrompt: recipe.imagePrompt,
    keyword,
  })

  await appendLog(recipeId, logEntry("Image Prompt", "done", `Using image prompt (${imagePrompt.length} chars)`))
  await new Promise((r) => setTimeout(r, 2000)) // rate-limit pause

  const imageVariants: Array<{ label: string; url: string; prompt: string }> = []
  let heroImageUrl: string | null = null

  for (let vi = 0; vi < IMAGE_VARIANT_COUNT; vi++) {
    try {
      await appendLog(recipeId, logEntry("Image Gen", "running", `Variant ${vi + 1}/${IMAGE_VARIANT_COUNT}`))
      const buffer = await runImage(imagePrompt)
      await appendLog(recipeId, logEntry("Image Gen", "done", `Variant ${vi + 1} generated — ${buffer.length} bytes`))

      const imageUrl = await uploadImage(buffer, `${recipe.title}-v${vi}`)
      await appendLog(recipeId, logEntry("Image Upload", "done", `Uploaded to Cloudinary — v${vi}`))

      imageVariants.push({ label: `Variant ${vi + 1}`, url: imageUrl, prompt: imagePrompt })
      if (!heroImageUrl) heroImageUrl = imageUrl

      // Non-blocking image quality validation
      try {
        const imgValidation = await validateImage(imageUrl, { requireAltText: true, altText: recipe.title })
        if (!imgValidation.passed) {
          const issues = imgValidation.errors.map(e => e.message).join("; ")
          await appendLog(recipeId, logEntry("Image Validator", "done",
            `Variant ${vi + 1} has ${imgValidation.errors.length} issue(s): ${issues}`))
        }
      } catch (imgErr) {
        await appendLog(recipeId, logEntry("Image Validator", "error",
          `Validation failed for v${vi}: ${(imgErr as Error).message}`))
      }
    } catch (err) {
      degraded = true
      await logPipelineError({
        recipeId, stepName: `image-gen-v${vi}`,
        errorType: "unknown", message: (err as Error).message, severity: "warning",
      })
    }
  }

  return { heroImageUrl, imageVariants, degraded }
}
