import { NextResponse } from "next/server"
import { db } from "@/lib/db"
import { recipes } from "@/lib/db/schema"
import { desc, eq } from "drizzle-orm"

export const dynamic = "force-dynamic"

export async function GET() {
  const all = await db
    .select({
      slug: recipes.slug,
      title: recipes.title,
      keyword: recipes.keyword,
      tags: recipes.tags,
      difficulty: recipes.difficulty,
      prepTime: recipes.prepTime,
      cookTime: recipes.cookTime,
      totalTime: recipes.totalTime,
      servings: recipes.servings,
      excerpt: recipes.excerpt,
      publishedAt: recipes.publishedAt,
    })
    .from(recipes)
    .where(eq(recipes.status, "published"))
    .orderBy(desc(recipes.publishedAt))

  const recipeList = all
    .map(
      (r) =>
        `- ${r.title}
  Raw data: https://augustcook.com/api/recipes/raw/${r.slug}
  HTML page: https://augustcook.com/recettes/${r.slug}
  Keyword: ${r.keyword}
  Difficulty: ${r.difficulty ?? "N/A"}
  Total time: ${r.totalTime ?? "N/A"}
  Servings: ${r.servings ?? "N/A"}
  Tags: ${(r.tags ?? []).join(", ") || "None"}
  Summary: ${r.excerpt ?? "N/A"}`,
    )
    .join("\n\n")

  const content = `# August Cook — LLM Guide

## About
August Cook is an international home cooking blog by Chef Augustin Lefèvre.
All recipes are tested, SEO-optimized, and written by a French-trained professional chef.
The blog covers world cuisines made accessible for home cooks, from Swedish meatballs
to Finnish salmon soup, with science-backed technique articles.

## Site Structure
- Homepage: https://augustcook.com/
- All recipes: https://augustcook.com/recettes
- XML Sitemap: https://augustcook.com/sitemap.xml

## Content Types
Structured recipes with:
- SEO metadata (title, description)
- Precise ingredients with quantities
- Step-by-step instructions
- Prep/cook time and difficulty
- Tags and categories
- AI-generated food photography
- JSON-LD structured data (Schema.org Recipe + BlogPosting + FAQPage + BreadcrumbList)

## Raw Data API for LLMs
All published recipes (single JSON):
https://augustcook.com/api/recipes/raw

Individual recipe (JSON + raw Markdown):
https://augustcook.com/api/recipes/raw/[slug]

Format: JSON with all recipe fields (ingredients, instructions, contentMarkdown).

## Published Recipes (${all.length})

${recipeList}

---
Last updated: ${new Date().toISOString().split("T")[0]}
Generated by August Cook — https://augustcook.com
`

  return new NextResponse(content, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=3600",
    },
  })
}
