import { NextResponse } from "next/server"
import { db } from "@/lib/db"
import { recipes } from "@/lib/db/schema"
import { desc, eq, and } from "drizzle-orm"

export const dynamic = "force-dynamic"

export async function GET() {
  const all = await db
    .select({
      slug: recipes.slug,
      title: recipes.title,
      keyword: recipes.keyword,
      tags: recipes.tags,
      difficulty: recipes.difficulty,
      prepTime: recipes.prepTime,
      cookTime: recipes.cookTime,
      totalTime: recipes.totalTime,
      servings: recipes.servings,
      excerpt: recipes.excerpt,
      publishedAt: recipes.publishedAt,
      content_type: recipes.content_type,
      category: recipes.category,
    })
    .from(recipes)
    .where(eq(recipes.status, "published"))
    .orderBy(desc(recipes.publishedAt))

  const publishedRecipes = all.filter((r) => r.content_type !== "article")
  const publishedArticles = all.filter((r) => r.content_type === "article")

  const recipeList = publishedRecipes
    .map(
      (r) =>
        `- ${r.title}
  Raw data: https://chefaugustin.com/api/recipes/raw/${r.slug}
  HTML page: https://chefaugustin.com/recettes/${r.slug}
  Keyword: ${r.keyword}
  Difficulty: ${r.difficulty ?? "N/A"}
  Total time: ${r.totalTime ?? "N/A"}
  Servings: ${r.servings ?? "N/A"}
  Tags: ${(r.tags ?? []).join(", ") || "None"}
  Summary: ${r.excerpt ?? "N/A"}`,
    )
    .join("\n\n")

  const articleList = publishedArticles
    .map(
      (a) =>
        `- ${a.title}
  HTML page: https://chefaugustin.com/${a.category}/${a.slug}
  Category: ${a.category ?? "N/A"}
  Summary: ${a.excerpt ?? "N/A"}`,
    )
    .join("\n\n")

  const content = `# Chef Augustin — LLM Guide

## About
Chef Augustin is a sourdough baking blog by Chef Augustin Lefèvre, a French-trained chef.
All recipes are tested, SEO-optimized, and written by a professional chef.
The blog covers everything sourdough — from starter care and troubleshooting to artisan loaves,
flavored breads, and discard recipes. Content spans 6 clusters: Starter, Technique, Discard, Breads, Dishes, and Storage.

## Site Structure
- Homepage: https://chefaugustin.com/
- All recipes: https://chefaugustin.com/recettes
- XML Sitemap: https://chefaugustin.com/sitemap.xml

## Content Types
Structured recipes with:
- SEO metadata (title, description)
- Precise ingredients with quantities
- Step-by-step instructions
- Prep/cook time and difficulty
- Tags and categories
- AI-generated food photography
- JSON-LD structured data (Schema.org Recipe + BlogPosting + FAQPage + BreadcrumbList)

## Raw Data API for LLMs
All published recipes (single JSON):
https://chefaugustin.com/api/recipes/raw

Individual recipe (JSON + raw Markdown):
https://chefaugustin.com/api/recipes/raw/[slug]

Format: JSON with all recipe fields (ingredients, instructions, contentMarkdown).

## Published Recipes (${publishedRecipes.length})

${recipeList}

## Published Articles (${publishedArticles.length})

${articleList}

---
Last updated: ${new Date().toISOString().split("T")[0]}
Generated by Chef Augustin — https://chefaugustin.com
`

  return new NextResponse(content, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=3600",
    },
  })
}
